// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fedorov-dmitry/go-test-api/internal (interfaces: CurrencyStorage,CurrencyRateSource)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=/Users/dmitriy/Documents/Repo/go-test-api/internal/mocks/currency_rate.go github.com/fedorov-dmitry/go-test-api/internal CurrencyStorage,CurrencyRateSource
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	internal "github.com/fedorov-dmitry/go-test-api/internal"
	gomock "go.uber.org/mock/gomock"
)

// MockCurrencyStorage is a mock of CurrencyStorage interface.
type MockCurrencyStorage struct {
	ctrl     *gomock.Controller
	recorder *MockCurrencyStorageMockRecorder
	isgomock struct{}
}

// MockCurrencyStorageMockRecorder is the mock recorder for MockCurrencyStorage.
type MockCurrencyStorageMockRecorder struct {
	mock *MockCurrencyStorage
}

// NewMockCurrencyStorage creates a new mock instance.
func NewMockCurrencyStorage(ctrl *gomock.Controller) *MockCurrencyStorage {
	mock := &MockCurrencyStorage{ctrl: ctrl}
	mock.recorder = &MockCurrencyStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurrencyStorage) EXPECT() *MockCurrencyStorageMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCurrencyStorage) Get(ctx context.Context, baseCurrency, currency internal.Currency, date time.Time) (internal.CurrencyRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, baseCurrency, currency, date)
	ret0, _ := ret[0].(internal.CurrencyRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCurrencyStorageMockRecorder) Get(ctx, baseCurrency, currency, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCurrencyStorage)(nil).Get), ctx, baseCurrency, currency, date)
}

// GetMany mocks base method.
func (m *MockCurrencyStorage) GetMany(ctx context.Context, baseCurrency internal.Currency, date time.Time) ([]internal.CurrencyRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMany", ctx, baseCurrency, date)
	ret0, _ := ret[0].([]internal.CurrencyRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMany indicates an expected call of GetMany.
func (mr *MockCurrencyStorageMockRecorder) GetMany(ctx, baseCurrency, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMany", reflect.TypeOf((*MockCurrencyStorage)(nil).GetMany), ctx, baseCurrency, date)
}

// Set mocks base method.
func (m *MockCurrencyStorage) Set(ctx context.Context, currency internal.CurrencyRate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, currency)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCurrencyStorageMockRecorder) Set(ctx, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCurrencyStorage)(nil).Set), ctx, currency)
}

// MockCurrencyRateSource is a mock of CurrencyRateSource interface.
type MockCurrencyRateSource struct {
	ctrl     *gomock.Controller
	recorder *MockCurrencyRateSourceMockRecorder
	isgomock struct{}
}

// MockCurrencyRateSourceMockRecorder is the mock recorder for MockCurrencyRateSource.
type MockCurrencyRateSourceMockRecorder struct {
	mock *MockCurrencyRateSource
}

// NewMockCurrencyRateSource creates a new mock instance.
func NewMockCurrencyRateSource(ctrl *gomock.Controller) *MockCurrencyRateSource {
	mock := &MockCurrencyRateSource{ctrl: ctrl}
	mock.recorder = &MockCurrencyRateSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurrencyRateSource) EXPECT() *MockCurrencyRateSourceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCurrencyRateSource) Get(baseCurrency internal.Currency, currencies []internal.Currency, date time.Time) ([]internal.CurrencyRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", baseCurrency, currencies, date)
	ret0, _ := ret[0].([]internal.CurrencyRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCurrencyRateSourceMockRecorder) Get(baseCurrency, currencies, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCurrencyRateSource)(nil).Get), baseCurrency, currencies, date)
}
