// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fedorov-dmitry/go-test-api/internal/api (interfaces: CurrencyRepository)
//
// Generated by this command:
//
//	mockgen -package=apimocks -destination=/Users/dmitriy/Documents/Repo/go-test-api/internal/api/mocks/mock_api.go github.com/fedorov-dmitry/go-test-api/internal/api CurrencyRepository
//

// Package apimocks is a generated GoMock package.
package apimocks

import (
	context "context"
	reflect "reflect"
	time "time"

	internal "github.com/fedorov-dmitry/go-test-api/internal"
	gomock "go.uber.org/mock/gomock"
)

// MockCurrencyRepository is a mock of CurrencyRepository interface.
type MockCurrencyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCurrencyRepositoryMockRecorder
	isgomock struct{}
}

// MockCurrencyRepositoryMockRecorder is the mock recorder for MockCurrencyRepository.
type MockCurrencyRepositoryMockRecorder struct {
	mock *MockCurrencyRepository
}

// NewMockCurrencyRepository creates a new mock instance.
func NewMockCurrencyRepository(ctrl *gomock.Controller) *MockCurrencyRepository {
	mock := &MockCurrencyRepository{ctrl: ctrl}
	mock.recorder = &MockCurrencyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurrencyRepository) EXPECT() *MockCurrencyRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCurrencyRepository) Create(ctx context.Context, date time.Time, baseCurrency, currency internal.Currency, rate float64) (internal.CurrencyRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, date, baseCurrency, currency, rate)
	ret0, _ := ret[0].(internal.CurrencyRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCurrencyRepositoryMockRecorder) Create(ctx, date, baseCurrency, currency, rate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCurrencyRepository)(nil).Create), ctx, date, baseCurrency, currency, rate)
}

// Get mocks base method.
func (m *MockCurrencyRepository) Get(ctx context.Context, baseCurrency, currency internal.Currency, date time.Time) (internal.CurrencyRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, baseCurrency, currency, date)
	ret0, _ := ret[0].(internal.CurrencyRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCurrencyRepositoryMockRecorder) Get(ctx, baseCurrency, currency, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCurrencyRepository)(nil).Get), ctx, baseCurrency, currency, date)
}

// GetMany mocks base method.
func (m *MockCurrencyRepository) GetMany(ctx context.Context, baseCurrency internal.Currency, date time.Time) ([]internal.CurrencyRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMany", ctx, baseCurrency, date)
	ret0, _ := ret[0].([]internal.CurrencyRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMany indicates an expected call of GetMany.
func (mr *MockCurrencyRepositoryMockRecorder) GetMany(ctx, baseCurrency, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMany", reflect.TypeOf((*MockCurrencyRepository)(nil).GetMany), ctx, baseCurrency, date)
}
